// ReleaseNotesView.swift
// Commonplace
//
// Displays app release notes accessible from Settings → About.
// Shows the latest version prominently with a full history below.
// Add new versions to the top of the `releases` array as they ship.

import SwiftUI

struct ReleaseNotesView: View {
    @EnvironmentObject var themeManager: ThemeManager
    var style: any AppThemeStyle { themeManager.style }
    var accent: Color { style.accent }

    struct Release: Identifiable {
        let id = UUID()
        let version: String
        let title: String
        let notes: [String]
    }

    let releases: [Release] = [
        Release(
            version: "1.7.1",
            title: "The Wolf, The Fixer",
            notes: [
                "Typing in Inkwell theme now correctly shows the serif font in real time",
                "Keyboard no longer covers text fields — content stays comfortably visible while typing",
                "Home tab redesigned as a bookmarks dashboard — Collections, Entries, People, and Tags each get their own section",
                "Favorites retired — everything is now a Bookmark for simplicity",
                "Person detail page redesigned with centered avatar, gold ring, and elegant formal layout",
                "Profile photos can now be cropped when setting a person's avatar",
                "Media detail view now shows proper rectangular movie and TV posters",
                "Sticky entries improved — new items animate in at the top, title field jumps straight to Add Item, return key clears correctly"
            ]
        ),
        Release(
            version: "1.7",
            title: "Power to the People",
            notes: [
                "Tag people on any entry using the new People section on entry detail views",
                "People appear in the Library tab alongside Collections and Tags",
                "Each person gets a full detail view with a photo background, bio, and birthday",
                "Tap Edit to update a person's photo, name, bio, and birthday",
                "All entries tagged with a person are collected on their detail page",
                "People are automatically created the first time you tag someone"
            ]
        ),
        Release(
            version: "1.6.1",
            title: "Under the Hood",
            notes: [
                "Search is now dramatically more complete — location, habits, journal emojis, link URLs, and media descriptions are all searchable",
                "Photos shared via the share extension now get text extracted automatically",
                "Location now appears correctly on entries saved via the share extension",
                "Importing an archive now makes entries immediately searchable",
                "Importing an archive now correctly restores all tags",
                "Bookmark and favorite buttons added to all entry detail views",
                "Media entry status and star rating now respond instantly with no lag"
            ]
        ),
        Release(
            version: "1.6",
            title: "Good Morning. How are you?",
            notes: [
                "Daily journaling prompts — set your weather, mood, and vibe to unlock two personalized prompts each morning",
                "Prompts are generated by Claude based on your emoji combination — completely private, only three characters are ever sent",
                "One prompt to reflect, one prompt to act — dismiss for the day if you're not feeling it",
                "Settings moved to the Home tab for easier access",
                "Settings is now a full page instead of a sheet — export and import work much more reliably",
                "Habits get their own dedicated page with drag-to-reorder"
            ]
        ),
        Release(
            version: "1.5",
            title: "I'll Have What She's Having",
            notes: [
                "Media entry type — track movies and TV shows you're watching",
                "Search any title and pull in cover art, genre, runtime, and more automatically",
                "Mark anything as Want to Watch, In Progress, or Finished",
                "Rate what you've watched with a five star rating",
                "Keep a running log of thoughts as you watch",
                "Filter collections by watch status to build your perfect watchlist",
                "Share extension entries now appear in search immediately"
            ]
        ),
        Release(
            version: "1.4",
            title: "Sharing is Caring",
            notes: [
                "Share Extension — save links, images, text, and music directly from any app",
                "Apple Music links captured automatically with full track metadata",
                "Screenshots and images shared from other apps save instantly",
                "Markdown archive export — download your entire journal as a ZIP",
                "Release notes — you're reading them right now"
            ]
        ),
        Release(
            version: "1.3",
            title: "Big Kahuna Burger",
            notes: [
                "New Home dashboard with horizontal quick-access cards",
                "Full Apple Music playback — tap to play without leaving the app",
                "Tag bookmarking — pin tags to your Home tab",
                "Inkwell theme now renders serif fonts correctly throughout",
                "Photos automatically optimized to save storage",
                "Faster feed with async image loading and smart caching",
                "Export now checks iCloud sync before saving your archive",
                "Search now indexes all entries automatically on launch"
            ]
        ),
        Release(
            version: "1.2",
            title: "Music To My Ears",
            notes: [
                "Inkwell — a warm dark theme inspired by leather-bound books",
                "Music entry type — save and preview Apple Music tracks",
                "Improved collection filtering and organization"
            ]
        ),
        Release(
            version: "1.1",
            title: "Gotta Catch 'em All",
            notes: [
                "Collections — organize entries with custom filters and icons",
                "Performance improvements throughout the app",
                "Faster launch and smoother scrolling"
            ]
        ),
        Release(
            version: "1.0",
            title: "Now Presenting!",
            notes: [
                "Initial Release"
            ]
        ),
    ]

    var body: some View {
        List {
            // Latest version — prominent
            if let latest = releases.first {
                Section {
                    VStack(alignment: .leading, spacing: 12) {
                        HStack(alignment: .firstTextBaseline, spacing: 8) {
                            Text("Version \(latest.version)")
                                .font(style.usesSerifFonts
                                      ? .system(.title2, design: .serif)
                                      : .title2)
                                .fontWeight(.bold)
                                .foregroundStyle(style.primaryText)
                            Text("Latest")
                                .font(.caption)
                                .fontWeight(.semibold)
                                .padding(.horizontal, 8)
                                .padding(.vertical, 3)
                                .background(accent.opacity(0.15))
                                .foregroundStyle(accent)
                                .clipShape(Capsule())
                        }
                        Text(latest.title)
                            .font(style.usesSerifFonts
                                  ? .system(.subheadline, design: .serif)
                                  : .subheadline)
                            .foregroundStyle(style.secondaryText)
                        VStack(alignment: .leading, spacing: 8) {
                            ForEach(latest.notes, id: \.self) { note in
                                HStack(alignment: .top, spacing: 8) {
                                    Image(systemName: "sparkle")
                                        .font(.system(size: 10))
                                        .foregroundStyle(accent)
                                        .padding(.top, 3)
                                    Text(note)
                                        .font(style.usesSerifFonts
                                              ? .system(.body, design: .serif)
                                              : .body)
                                        .foregroundStyle(style.primaryText)
                                }
                            }
                        }
                    }
                    .padding(.vertical, 8)
                }
                .listRowBackground(style.usesSerifFonts ? style.surface : nil)

            }

            // Previous versions
            Section {
                ForEach(releases.dropFirst()) { release in
                    DisclosureGroup {
                        VStack(alignment: .leading, spacing: 8) {
                            ForEach(release.notes, id: \.self) { note in
                                HStack(alignment: .top, spacing: 8) {
                                    Circle()
                                        .fill(style.tertiaryText)
                                        .frame(width: 4, height: 4)
                                        .padding(.top, 6)
                                    Text(note)
                                        .font(style.usesSerifFonts
                                              ? .system(.subheadline, design: .serif)
                                              : .subheadline)
                                        .foregroundStyle(style.secondaryText)
                                }
                            }
                        }
                        .padding(.vertical, 4)
                    } label: {
                        HStack {
                            Text("Version \(release.version)")
                                .font(style.usesSerifFonts
                                      ? .system(.body, design: .serif)
                                      : .body)
                                .foregroundStyle(style.primaryText)
                            Spacer()
                            Text(release.title)
                                .font(.caption)
                                .foregroundStyle(style.tertiaryText)
                        }
                    }
                    .listRowBackground(style.usesSerifFonts ? style.surface : nil)
                }
            } header: {
                Text("Previous Versions")
                    .foregroundStyle(style.tertiaryText)
            }
        }
        .listStyle(.insetGrouped)
        .scrollContentBackground(style.usesSerifFonts ? .hidden : .visible)
        .background(style.usesSerifFonts ? style.background : Color(uiColor: .systemGroupedBackground))
        .navigationTitle("What's New")
        .navigationBarTitleDisplayMode(.inline)
    }
}
